### ISSUE TITLE
I sincerely invite you to join the development of SmartSql components.

### ISSUE THREAD

**Issue by ghd258** [EnterpriseLibrary/data-access-application-block#2]
https://github.com/Ahoo-Wang/SmartSql
I sincerely invite you to join the SmartSql component research and development, this component is better than data-access-application-block, and more flexible, you have such a high hand to join, participate in continuous improvement and optimization, this component will be more excellent, thank you.

**Comment by Chavoshi** [comment]
Hi @ghd258,
Thanks for your invitation. But at this time, I consider that, but at this time I'm really busy with a lot of stuffs, but absolutely I will take a look at in a near future.

**Comment by ghd258** [comment]
https://github.com/Ahoo-Wang/SmartSql
I sincerely invite you to join the SmartSql component research and development, this component is better than data-access-application-block, and more flexible, you have such a high hand to join, participate in continuous improvement and optimization, this component will be more excellent, thank you.

**Comment by Chavoshi** [comment]
I have already answered to your invitation one time and I do not know what are you looking for.
I am not beneficiary on any of the projects which I have put them here and I thought it might be helpful for another people as well, and also I am not looking for a solution in this area.
By the way thanks for your suggestion.
