### ISSUE TITLE
Why were LocalDB connection strings changed?

### ISSUE THREAD

**Issue by tsahi** [EnterpriseLibrary/data-access-application-block#27]
While working on fixing tests in [ExecuteXmlReaderFixture](https://github.com/EnterpriseLibrary/data-access-application-block/blob/77d25f609692c90c4fd284d61557774523a19957/source/Tests/Data.Tests/Sql/ExecuteXmlReaderFixture.cs#L18), I had a `System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server.` The source of the error is the connection string in https://github.com/EnterpriseLibrary/data-access-application-block/blob/77d25f609692c90c4fd284d61557774523a19957/source/Tests/Data.Tests/Microsoft.Practices.EnterpriseLibrary.Data.Tests.dll.config#L34-L37 where the `server` attribute was changed from `(localdb)\v11`, which points to an instance of SQL Server 2012 LocalDB (which I happen to have installed) to just `(local)`, which points to a full SQL Server, which I don't have (and is quite difficult to host on a developer station).
I also noticed a very similar file named testhost.dll.config was added to the project, with the same connection strings.
1. why was the `server` attribute changed, and how do you connect to a localDB without altering it back? I can change it to a newer version, such as 2016.
2. what is the purpose of testhost.dll.config? should this be updated too?

thanks,
Tsahi

**Comment by Chavoshi** [comment]
Hi Tashi,
There is no specific reason of using **localdb** and you can change it wherever is necessary and about the **testhost.dll.config**, technically it is the app.config of the test application. You can find out the reason of adding that from this thread: https://stackoverflow.com/a/54856425/593609
