### ISSUE TITLE
DatabaseProviderFactory.Create(String) fails for an ODBC provider under .NET Core

### ISSUE THREAD

**Issue by tsahi** [EnterpriseLibrary/data-access-application-block#32]
When trying to create a `GenericDatabase` in order to work with a `System.Data.Odbc` provider under .NET Core, `DatabaseProviderFactory.Create(String)` creates a `SqlDatabase` instead. This fails the test at https://github.com/EnterpriseLibrary/data-access-application-block/blob/27bedfcc43147c19e9620d983098d5fa8d54a025/source/Tests/Data.Tests/GenericDatabaseFixture.cs#L26-L35 under .NET Core. We should either:
1. Disable this test and remove support for ODBC under .NET Core
2. Add a dependency on [System.Data.Odbc](https://www.nuget.org/packages/System.Data.Odbc/) in .NET Core, which I believe will solve the issue (haven't tried yet).

What do you think?

As a side note, we should consider if `GenericDatabase` is the best fit for ODBC, since it doesn't support `DeriveParameters()`, while `OdbcCommandBuilder` does, depending on the underlying data source.

**Comment by tsahi** [comment]
From https://github.com/EnterpriseLibrary/data-access-application-block/blob/27bedfcc43147c19e9620d983098d5fa8d54a025/source/Tests/Data.Tests/Configuration/DatabaseProviderFactoryFixture.cs#L52 it looks like under netcore `DbProviderFactories.GetFactory()` returns a `SqlClientFactory` for any provider name it doesn't recognize, even bogus one.

**Comment by Chavoshi** [comment]
In this case, don't you think that deprecating ODBC support will be a better option? It means in case someone really needs to have support for a provider, implements it in a separate project.
I do not have a good feeling about this generalization.

**Comment by tsahi** [comment]
The main issue I see is that if there is an error in the provider name, we will provide the wrong Database, and I don't see a quick way to prevent that. We can test that the provider name is in `DbProviderFactories.GetFactoryClasses().Rows`, but this will hurt performance (caching can help). This is a problem that will happen with any non-existant provider, not just ODBC. Another option is to document it, so users are aware of it. (documentation is another issue that needs to be fixed in this project).

One of my long-term goals is to break down this package to separate packages for each provider. When Microsoft created it, .NET Framework supported everything - SQL Server, Oracle, OLE DB, ODBC etc. today SQL Server and Oracle are supported by separate packages, but people who need to use DAAB for SQL Server still carry a dependency on the Oracle Managed Data Access package. In that context, we can separate the support for ODBC to such a separate package.

What generalization do you mean?

**Comment by Chavoshi** [comment]
By generalization I exactly meant the thing which you completely and clearly explained it. Having a general tool to solve all problems can cause lots performance issues, so I 100% agree with splitting the project.

I've added you as a contributor in this project.

**Comment by tsahi** [comment]
I suggest we'll leave this issue open for now, to help track the problem, until we make a design of how to break DAAB to smaller packages.

**Comment by tsahi** [comment]
Since this issue is a result of code bug and not .NET Core issue, i'm closing this.
