### ISSUE TITLE
Can you update the DLL of NuGet application to the latest version?

### ISSUE THREAD

**Issue by ghd258** [EnterpriseLibrary/data-access-application-block#4]
Can you update the DLL of NuGet application to the latest version, including other libraries

**Comment by ghd258** [comment]
support similar MyBatis framework, support Sql statements in XML file configuration

**Comment by ghd258** [comment]
Has the work been updated?

**Comment by Chavoshi** [comment]
Still working on it. As I said it might take up to end of September.

**Comment by Chavoshi** [comment]
Let me update the packages with the new version, so for your next requests you can do it by yourself and give a pull request.
