### ISSUE TITLE
SqlClient Data Provider -Error

### ISSUE THREAD

**Issue by jigarce** [EnterpriseLibrary/data-access-application-block#50]
Hi,

Sometimes  I receive below error while fetching data. let me know if you have any idea regarding this bug.

Error source :  SqlClient Data Provider

 

I am using .NET core 3.1 using windows server.

Let me know if you come across any solution for above error , Error is not frequent 

Regards,
Jigar

**Comment by tsahi** [comment]
Can you show a code example where this happens?

**Comment by jigarce** [comment]
remove it
