### ISSUE TITLE
Npgsql provider with NET Core

### ISSUE THREAD

**Issue by dillanmann** [EnterpriseLibrary/data-access-application-block#9]
Hi all,

I am having a bit of trouble with using this library with PostgreSQL. I can get the connection string in just fine but I keep getting the exception `'The connection string for the database 'PostgreSQL' does not exist or does not have a valid provider.'`

My config looks like:

```
   <connectionStrings>
      <clear />
      <add name="PostgreSQL" providerName="Npgsql" connectionString="host=localhost;user id=postgres;password=test;database=test;MaxPoolSize=100;CommandTimeout=60;Enlist=true" />
   </connectionStrings>
```

From investigation it seems like NET Core has a different way of registered providers with the DbProviderFactories but I can't work out how to do it. Any idea would be much appreciated! Thanks.

**Comment by Chavoshi** [comment]
Hi,
You need to register your provider in you application configuration file.

Follow this example: https://github.com/Chavoshi/EnterpriseLibrary.NetCore/blob/master/Examples/EnterpriseLibrary.Test.MySql/EnterpriseLibrary.Test.MySql/App.config

**Comment by dillanmann** [comment]
Thanks, I will try this and get back to you!

**Comment by dillanmann** [comment]
We no longer require this, but thanks for your help.
